# These are supported funding model platforms
# Uncomment and add your funding links when ready

# github: [dabbleintech]
# patreon: # your-patreon-username
# ko_fi: # your-ko-fi-username
# custom: # your-custom-donation-link
